import random

question_data = [
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Easy",
        "question": "HTML stands for HyperText Markup Language.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Medium",
        "question": "CSS stands for Cascading Style Sheets.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Hard",
        "question": "Binary search has a time complexity of O(log n).",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Easy",
        "question": "Python is a low-level language.",
        "correct_answer": False,
        "incorrect_answers": [True],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Medium",
        "question": "CPU stands for Central Processing Unit.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Hard",
        "question": "A compiler translates code from one language to another.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Easy",
        "question": "HTTP uses port 80 by default.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Medium",
        "question": "A linked list is a linear data structure.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Hard",
        "question": "An API is used for building software applications.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Easy",
        "question": "Firewalls protect networks from unauthorized access.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Medium",
        "question": "Recursion is a programming technique where a function calls itself.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Hard",
        "question": "SQL stands for Structured Query Language.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Easy",
        "question": "RAM is non-volatile memory.",
        "correct_answer": False,
        "incorrect_answers": [True],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Medium",
        "question": "An algorithm is a step-by-step procedure for solving a problem.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Hard",
        "question": "Git is a version control system.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Easy",
        "question": "Network protocols define rules for communication between devices.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Medium",
        "question": "Object-oriented programming is based on the concept of objects.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Hard",
        "question": "HTTP is a protocol for transmitting data over the internet.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Easy",
        "question": "JSON stands for JavaScript Object Notation.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
    {
        "category": "Computer Science",
        "type": "Boolean",
        "difficulty": "Medium",
        "question": "Linux is a kernel used in operating systems like Ubuntu.",
        "correct_answer": True,
        "incorrect_answers": [False],
    },
]
